name: Pull, Retag, and Push Docker Image

on: 
  workflow_dispatch
  push:
    branches:
      - main  # Set this to the branch that should trigger this action

jobs:
  repush-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from GitHub Container Registry
        run: docker pull ghcr.io/aurora-develop/aurora:latest

      - name: Tag the Docker image
        run: docker tag ghcr.io/aurora-develop/aurora xiaoxiaofeihh/my35:latest

      - name: Push the tagged image to Docker Hub
        run: docker push xiaoxiaofeihh/my35:latest
